services:
  server:
    build:
      context: ./server
      target: dev
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  web:
    build:
      context: ./web
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./web:/app
      - /app/node_modules

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_cogna
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
