version: '3.8'

services:
  server:
    build:
      context: ./server
      target: prod
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      - server
