services:
  server:
    build:
      context: ./server
      target: prod
    ports:
      - "8000:8000"
    env_file: ./server/.env.test
    depends_on:
      - test-db

  db-migration:
    build:
      context: ./server
      target: dev
    command: pnpm migrate-and-seed
    env_file: ./server/.env.test
    depends_on:
      - test-db

  backend-test:
    build:
      context: ./server
      target: dev
    command: pnpm test
    env_file: ./server/.env.test
    environment:
      - NODE_ENV=test
    depends_on:
      - test-db

  frontend:
    build:
      context: ./web
      target: prod
    environment:
      - API_URL=http://server:8000
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - web_src:/app/

  cypress:
      image: "cypress/included:14.5.1"
      depends_on:
        - frontend
        - server
      environment:
        - CYPRESS_baseUrl=http://frontend:3000
        - CYPRESS_API_URL=http://server:8000
      working_dir: /e2e
      volumes:
        - web_src:/e2e

  test-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_cogna_test
    ports:
      - "25432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
  web_src:
