name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose -f docker-compose.test.yml build

      - name: Run server tests
        run: docker compose -f docker-compose.test.yml up backend-test --exit-code-from backend-test

      - name: Run migrations
        run: docker compose -f docker-compose.test.yml up db-migration

      - name: Run E2E tests
        run: docker compose -f docker-compose.test.yml up cypress --exit-code-from cypress
