name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run all tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
