name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install web dependencies
        run: pnpm install
        working-directory: ./web

      - name: Run TypeScript check on web
        run: pnpm tsc --noEmit
        working-directory: ./web

      - name: Run server tests
        run: docker compose -f docker-compose.test.yml up backend-test

      - name: Run E2E tests
        run: docker compose -f docker-compose.test.yml up cypress
